### ISSUE TITLE
HomeAssistant log is showing errors 

### ISSUE THREAD

**Issue by rouloy** [elad-bar/ha-shinobi#44]
HomeAssistant logs keep showing errors. Shinobi Hub version is 79f60848a40766f53cb0a3944cecedaa0e0b0cbc . Shinobi was not restarted

2023-02-02 18:08:42.016 DEBUG (MainThread) [custom_components.shinobi.component.api.api] Updating data from Shinobi Video Server (10.0.0.10)
2023-02-02 18:08:42.016 DEBUG (MainThread) [custom_components.shinobi.component.api.api] Retrieving monitors
2023-02-02 18:08:42.016 DEBUG (MainThread) [custom_components.shinobi.component.api.api] GET http://10.0.0.10:8090/z3OA9d7FOExdaGjva7gjEEbbILUQ3A/monitor/Jr1ZGE7KEB
2023-02-02 18:08:42.021 DEBUG (MainThread) [custom_components.shinobi.component.api.api] Status of http://10.0.0.10:8090/z3OA9d7FOExdaGjva7gjEEbbILUQ3A/monitor/Jr1ZGE7KEB: 200
2023-02-02 18:08:42.777 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:43.778 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:44.778 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:45.779 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:46.780 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:47.782 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:48.783 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:49.784 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:50.785 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:51.785 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:52.787 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:53.787 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:54.788 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:55.789 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:56.790 INFO (MainThread) [custom_components.shinobi.component.api.websocket] Message queue is empty, will try to resample in a second
2023-02-02 18:08:57.023 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/shinobi/component/managers/home_assistant.py", line 61, in async_send_heartbeat
    await self.ws.async_send_heartbeat()
  File "/config/custom_components/shinobi/component/api/websocket.py", line 171, in async_send_heartbeat
    await self._ws.ping(SHINOBI_WS_PING_MESSAGE)
  File "/usr/lib/python3.10/site-packages/aiohttp/client_ws.py", line 143, in ping
    await self._writer.ping(message)
  File "/usr/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Comment by elad-bar** [comment]
pls check with latest [v2.0.31](https://github.com/elad-bar/ha-shinobi/releases/tag/v2.0.31) whether the issue solved or not

thanks

**Comment by rouloy** [comment]
Hi, no more errors in the log

**Comment by elad-bar** [comment]
Great, can I close the issue?

Thanks
